$DynamicModuleContent = '# Auto-Generated by Makaio
$Files  = @( Get-ChildItem -Path $PSScriptRoot\*.ps1 -ErrorAction SilentlyContinue )

foreach($import in $Files)
{
    Try
    {
        Import-Module -Name $import.FullName -Force -ErrorAction Stop
    }
    Catch
    {
        Write-Error -Message "Failed to import function $($import.fullname): $_"
    }
}'

$MetaFileTemplate = @"
`$meta = @{
    Name = "{NAME}"
    OutputPath = "{OUTPUTPATH}"
    Guid = "{GUID}"
    Author = "{AUTHOR}"
    CompanyName = "{COMPANYNAME}"
    Copyright = "{COPYRIGHT}"
    Version = "{VERSION}"
    PublicFunctions = @({PUBLICFUNCTIONS})
}
"@

$Defaults = @{
    OutputPath = "bld"
    Version = "0.0.1"
}
